### ISSUE TITLE
Unable to load ca and server certificates in mosquitto conf file

### ISSUE THREAD

**Issue by sanchitads** [thesuavedeveloper/youtube-lab#1]
facing error when i try to run mosquitto conf file. it says openssl permission denied.

<img width="754" alt="Capture1" src="https://user-images.githubusercontent.com/92909253/138222194-02898e66-a7f0-4c4b-af5c-5489f3ba7005.PNG">

**Comment by thesuavedeveloper** [comment]
Hey, I'm checking but I can't seem to find the this command that you are running in the [list of commands](https://github.com/thesuavedeveloper/youtube-labs/blob/main/How%20to%20setup%20a%20Secure%20Mosquito%20MQTT%20Broker%20on%20AWS/install_mosquitto.txt) 

Can you be sure all steps were successful before this point? and also please let me know exactly what step are you at?

**Comment by sanchitads** [comment]
Hi!! this is the command...$ **sudo systemctl restart mosquitto**. In my case it doesnot work like that. everytime i do changes in mosquitto conf file, i run **sudo lsof -iTCP -sTCP:LISTEN -n -P** and kill mosquitto pid by running **sudo kill** . then i rerun the mosquitto broker by **sudo mosquitto -c /etc/mosquitto/conf.d/mosquitto.conf.** basically this is restarting mosquitto broker so that changes take effect. all steps were successful before this. I can open the pem file so i go ahead and add the pem files in mosquitto conf. but here problem is coming. i have tried again by reissuing certificates still the same. also tried using openssl generated .crt file but same problem. can it be related to ec2 side configuration error? Please find below conf file.
<img width="576" alt="Capture3" src="https://user-images.githubusercontent.com/92909253/138369091-ac4bf1ce-6a9f-4354-b9e2-e809575c88ab.PNG">

**Comment by sanchitads** [comment]
above problem is solved. I used **sudo su** 
**chmod 755 /etc/letsencrypt/** . able to run conf file successfully as root user. Now i am not able to download mqtt.fx. can you please share the link?

**Comment by thesuavedeveloper** [comment]
Ohh glad you got it solved. New versions of mqtt.fx are paid, but this one is free: 

http://www.jensd.de/apps/mqttfx/1.7.1/

I'm closing the issue as it was resolved.
